service: tooling-s3-sqs
frameworkVersion: "2"

provider:
  name: aws
  region: "us-east-1"
  profile: node-serveless
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-jest-plugin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
